// Code generated by goctl. DO NOT EDIT.
// Source: travel.proto

package travel

import (
	"context"

	"XavierLookLook/app/travel/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddHomestayActivityReq      = pb.AddHomestayActivityReq
	AddHomestayActivityResp     = pb.AddHomestayActivityResp
	AddHomestayBusinessReq      = pb.AddHomestayBusinessReq
	AddHomestayBusinessResp     = pb.AddHomestayBusinessResp
	AddHomestayCommentReq       = pb.AddHomestayCommentReq
	AddHomestayCommentResp      = pb.AddHomestayCommentResp
	AddHomestayReq              = pb.AddHomestayReq
	AddHomestayResp             = pb.AddHomestayResp
	DelHomestayActivityReq      = pb.DelHomestayActivityReq
	DelHomestayActivityResp     = pb.DelHomestayActivityResp
	DelHomestayBusinessReq      = pb.DelHomestayBusinessReq
	DelHomestayBusinessResp     = pb.DelHomestayBusinessResp
	DelHomestayCommentReq       = pb.DelHomestayCommentReq
	DelHomestayCommentResp      = pb.DelHomestayCommentResp
	DelHomestayReq              = pb.DelHomestayReq
	DelHomestayResp             = pb.DelHomestayResp
	GetHomestayActivityByIdReq  = pb.GetHomestayActivityByIdReq
	GetHomestayActivityByIdResp = pb.GetHomestayActivityByIdResp
	GetHomestayBusinessByIdReq  = pb.GetHomestayBusinessByIdReq
	GetHomestayBusinessByIdResp = pb.GetHomestayBusinessByIdResp
	GetHomestayByIdReq          = pb.GetHomestayByIdReq
	GetHomestayByIdResp         = pb.GetHomestayByIdResp
	GetHomestayCommentByIdReq   = pb.GetHomestayCommentByIdReq
	GetHomestayCommentByIdResp  = pb.GetHomestayCommentByIdResp
	Homestay                    = pb.Homestay
	HomestayActivity            = pb.HomestayActivity
	HomestayBusiness            = pb.HomestayBusiness
	HomestayComment             = pb.HomestayComment
	SearchHomestayActivityReq   = pb.SearchHomestayActivityReq
	SearchHomestayActivityResp  = pb.SearchHomestayActivityResp
	SearchHomestayBusinessReq   = pb.SearchHomestayBusinessReq
	SearchHomestayBusinessResp  = pb.SearchHomestayBusinessResp
	SearchHomestayCommentReq    = pb.SearchHomestayCommentReq
	SearchHomestayCommentResp   = pb.SearchHomestayCommentResp
	SearchHomestayReq           = pb.SearchHomestayReq
	SearchHomestayResp          = pb.SearchHomestayResp
	UpdateHomestayActivityReq   = pb.UpdateHomestayActivityReq
	UpdateHomestayActivityResp  = pb.UpdateHomestayActivityResp
	UpdateHomestayBusinessReq   = pb.UpdateHomestayBusinessReq
	UpdateHomestayBusinessResp  = pb.UpdateHomestayBusinessResp
	UpdateHomestayCommentReq    = pb.UpdateHomestayCommentReq
	UpdateHomestayCommentResp   = pb.UpdateHomestayCommentResp
	UpdateHomestayReq           = pb.UpdateHomestayReq
	UpdateHomestayResp          = pb.UpdateHomestayResp

	Travel interface {
		// -----------------------每一间民宿-----------------------
		AddHomestay(ctx context.Context, in *AddHomestayReq, opts ...grpc.CallOption) (*AddHomestayResp, error)
		UpdateHomestay(ctx context.Context, in *UpdateHomestayReq, opts ...grpc.CallOption) (*UpdateHomestayResp, error)
		DelHomestay(ctx context.Context, in *DelHomestayReq, opts ...grpc.CallOption) (*DelHomestayResp, error)
		GetHomestayById(ctx context.Context, in *GetHomestayByIdReq, opts ...grpc.CallOption) (*GetHomestayByIdResp, error)
		SearchHomestay(ctx context.Context, in *SearchHomestayReq, opts ...grpc.CallOption) (*SearchHomestayResp, error)
		// -----------------------每一间民宿-----------------------
		AddHomestayActivity(ctx context.Context, in *AddHomestayActivityReq, opts ...grpc.CallOption) (*AddHomestayActivityResp, error)
		UpdateHomestayActivity(ctx context.Context, in *UpdateHomestayActivityReq, opts ...grpc.CallOption) (*UpdateHomestayActivityResp, error)
		DelHomestayActivity(ctx context.Context, in *DelHomestayActivityReq, opts ...grpc.CallOption) (*DelHomestayActivityResp, error)
		GetHomestayActivityById(ctx context.Context, in *GetHomestayActivityByIdReq, opts ...grpc.CallOption) (*GetHomestayActivityByIdResp, error)
		SearchHomestayActivity(ctx context.Context, in *SearchHomestayActivityReq, opts ...grpc.CallOption) (*SearchHomestayActivityResp, error)
		// -----------------------民宿店铺-----------------------
		AddHomestayBusiness(ctx context.Context, in *AddHomestayBusinessReq, opts ...grpc.CallOption) (*AddHomestayBusinessResp, error)
		UpdateHomestayBusiness(ctx context.Context, in *UpdateHomestayBusinessReq, opts ...grpc.CallOption) (*UpdateHomestayBusinessResp, error)
		DelHomestayBusiness(ctx context.Context, in *DelHomestayBusinessReq, opts ...grpc.CallOption) (*DelHomestayBusinessResp, error)
		GetHomestayBusinessById(ctx context.Context, in *GetHomestayBusinessByIdReq, opts ...grpc.CallOption) (*GetHomestayBusinessByIdResp, error)
		SearchHomestayBusiness(ctx context.Context, in *SearchHomestayBusinessReq, opts ...grpc.CallOption) (*SearchHomestayBusinessResp, error)
		// -----------------------民宿评价-----------------------
		AddHomestayComment(ctx context.Context, in *AddHomestayCommentReq, opts ...grpc.CallOption) (*AddHomestayCommentResp, error)
		UpdateHomestayComment(ctx context.Context, in *UpdateHomestayCommentReq, opts ...grpc.CallOption) (*UpdateHomestayCommentResp, error)
		DelHomestayComment(ctx context.Context, in *DelHomestayCommentReq, opts ...grpc.CallOption) (*DelHomestayCommentResp, error)
		GetHomestayCommentById(ctx context.Context, in *GetHomestayCommentByIdReq, opts ...grpc.CallOption) (*GetHomestayCommentByIdResp, error)
		SearchHomestayComment(ctx context.Context, in *SearchHomestayCommentReq, opts ...grpc.CallOption) (*SearchHomestayCommentResp, error)
	}

	defaultTravel struct {
		cli zrpc.Client
	}
)

func NewTravel(cli zrpc.Client) Travel {
	return &defaultTravel{
		cli: cli,
	}
}

// -----------------------每一间民宿-----------------------
func (m *defaultTravel) AddHomestay(ctx context.Context, in *AddHomestayReq, opts ...grpc.CallOption) (*AddHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.AddHomestay(ctx, in, opts...)
}

func (m *defaultTravel) UpdateHomestay(ctx context.Context, in *UpdateHomestayReq, opts ...grpc.CallOption) (*UpdateHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.UpdateHomestay(ctx, in, opts...)
}

func (m *defaultTravel) DelHomestay(ctx context.Context, in *DelHomestayReq, opts ...grpc.CallOption) (*DelHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.DelHomestay(ctx, in, opts...)
}

func (m *defaultTravel) GetHomestayById(ctx context.Context, in *GetHomestayByIdReq, opts ...grpc.CallOption) (*GetHomestayByIdResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.GetHomestayById(ctx, in, opts...)
}

func (m *defaultTravel) SearchHomestay(ctx context.Context, in *SearchHomestayReq, opts ...grpc.CallOption) (*SearchHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.SearchHomestay(ctx, in, opts...)
}

// -----------------------每一间民宿-----------------------
func (m *defaultTravel) AddHomestayActivity(ctx context.Context, in *AddHomestayActivityReq, opts ...grpc.CallOption) (*AddHomestayActivityResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.AddHomestayActivity(ctx, in, opts...)
}

func (m *defaultTravel) UpdateHomestayActivity(ctx context.Context, in *UpdateHomestayActivityReq, opts ...grpc.CallOption) (*UpdateHomestayActivityResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.UpdateHomestayActivity(ctx, in, opts...)
}

func (m *defaultTravel) DelHomestayActivity(ctx context.Context, in *DelHomestayActivityReq, opts ...grpc.CallOption) (*DelHomestayActivityResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.DelHomestayActivity(ctx, in, opts...)
}

func (m *defaultTravel) GetHomestayActivityById(ctx context.Context, in *GetHomestayActivityByIdReq, opts ...grpc.CallOption) (*GetHomestayActivityByIdResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.GetHomestayActivityById(ctx, in, opts...)
}

func (m *defaultTravel) SearchHomestayActivity(ctx context.Context, in *SearchHomestayActivityReq, opts ...grpc.CallOption) (*SearchHomestayActivityResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.SearchHomestayActivity(ctx, in, opts...)
}

// -----------------------民宿店铺-----------------------
func (m *defaultTravel) AddHomestayBusiness(ctx context.Context, in *AddHomestayBusinessReq, opts ...grpc.CallOption) (*AddHomestayBusinessResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.AddHomestayBusiness(ctx, in, opts...)
}

func (m *defaultTravel) UpdateHomestayBusiness(ctx context.Context, in *UpdateHomestayBusinessReq, opts ...grpc.CallOption) (*UpdateHomestayBusinessResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.UpdateHomestayBusiness(ctx, in, opts...)
}

func (m *defaultTravel) DelHomestayBusiness(ctx context.Context, in *DelHomestayBusinessReq, opts ...grpc.CallOption) (*DelHomestayBusinessResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.DelHomestayBusiness(ctx, in, opts...)
}

func (m *defaultTravel) GetHomestayBusinessById(ctx context.Context, in *GetHomestayBusinessByIdReq, opts ...grpc.CallOption) (*GetHomestayBusinessByIdResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.GetHomestayBusinessById(ctx, in, opts...)
}

func (m *defaultTravel) SearchHomestayBusiness(ctx context.Context, in *SearchHomestayBusinessReq, opts ...grpc.CallOption) (*SearchHomestayBusinessResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.SearchHomestayBusiness(ctx, in, opts...)
}

// -----------------------民宿评价-----------------------
func (m *defaultTravel) AddHomestayComment(ctx context.Context, in *AddHomestayCommentReq, opts ...grpc.CallOption) (*AddHomestayCommentResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.AddHomestayComment(ctx, in, opts...)
}

func (m *defaultTravel) UpdateHomestayComment(ctx context.Context, in *UpdateHomestayCommentReq, opts ...grpc.CallOption) (*UpdateHomestayCommentResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.UpdateHomestayComment(ctx, in, opts...)
}

func (m *defaultTravel) DelHomestayComment(ctx context.Context, in *DelHomestayCommentReq, opts ...grpc.CallOption) (*DelHomestayCommentResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.DelHomestayComment(ctx, in, opts...)
}

func (m *defaultTravel) GetHomestayCommentById(ctx context.Context, in *GetHomestayCommentByIdReq, opts ...grpc.CallOption) (*GetHomestayCommentByIdResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.GetHomestayCommentById(ctx, in, opts...)
}

func (m *defaultTravel) SearchHomestayComment(ctx context.Context, in *SearchHomestayCommentReq, opts ...grpc.CallOption) (*SearchHomestayCommentResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.SearchHomestayComment(ctx, in, opts...)
}
