// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v4.25.3
// source: travel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Homestay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title               string  `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	SubTitle            string  `protobuf:"bytes,3,opt,name=SubTitle,proto3" json:"SubTitle,omitempty"`
	Banner              string  `protobuf:"bytes,4,opt,name=Banner,proto3" json:"Banner,omitempty"`
	Info                string  `protobuf:"bytes,5,opt,name=Info,proto3" json:"Info,omitempty"`
	PeopleNum           int64   `protobuf:"varint,6,opt,name=PeopleNum,proto3" json:"PeopleNum,omitempty"`
	HomestayBusinessId  int64   `protobuf:"varint,7,opt,name=HomestayBusinessId,proto3" json:"HomestayBusinessId,omitempty"`
	UserId              int64   `protobuf:"varint,8,opt,name=UserId,proto3" json:"UserId,omitempty"`
	RowState            int64   `protobuf:"varint,9,opt,name=RowState,proto3" json:"RowState,omitempty"`
	RowType             int64   `protobuf:"varint,10,opt,name=RowType,proto3" json:"RowType,omitempty"`
	FoodInfo            string  `protobuf:"bytes,11,opt,name=FoodInfo,proto3" json:"FoodInfo,omitempty"`
	FoodPrice           float32 `protobuf:"fixed32,12,opt,name=FoodPrice,proto3" json:"FoodPrice,omitempty"`
	HomestayPrice       float32 `protobuf:"fixed32,13,opt,name=HomestayPrice,proto3" json:"HomestayPrice,omitempty"`
	MarketHomestayPrice float32 `protobuf:"fixed32,14,opt,name=MarketHomestayPrice,proto3" json:"MarketHomestayPrice,omitempty"`
}

func (x *Homestay) Reset() {
	*x = Homestay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Homestay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Homestay) ProtoMessage() {}

func (x *Homestay) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Homestay.ProtoReflect.Descriptor instead.
func (*Homestay) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{0}
}

func (x *Homestay) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Homestay) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Homestay) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *Homestay) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *Homestay) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Homestay) GetPeopleNum() int64 {
	if x != nil {
		return x.PeopleNum
	}
	return 0
}

func (x *Homestay) GetHomestayBusinessId() int64 {
	if x != nil {
		return x.HomestayBusinessId
	}
	return 0
}

func (x *Homestay) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Homestay) GetRowState() int64 {
	if x != nil {
		return x.RowState
	}
	return 0
}

func (x *Homestay) GetRowType() int64 {
	if x != nil {
		return x.RowType
	}
	return 0
}

func (x *Homestay) GetFoodInfo() string {
	if x != nil {
		return x.FoodInfo
	}
	return ""
}

func (x *Homestay) GetFoodPrice() float32 {
	if x != nil {
		return x.FoodPrice
	}
	return 0
}

func (x *Homestay) GetHomestayPrice() float32 {
	if x != nil {
		return x.HomestayPrice
	}
	return 0
}

func (x *Homestay) GetMarketHomestayPrice() float32 {
	if x != nil {
		return x.MarketHomestayPrice
	}
	return 0
}

type BusinessListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId             int64 `protobuf:"varint,1,opt,name=LastId,proto3" json:"LastId,omitempty"`
	PageSize           int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	HomestayBusinessId int64 `protobuf:"varint,3,opt,name=HomestayBusinessId,proto3" json:"HomestayBusinessId,omitempty"`
}

func (x *BusinessListReq) Reset() {
	*x = BusinessListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessListReq) ProtoMessage() {}

func (x *BusinessListReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessListReq.ProtoReflect.Descriptor instead.
func (*BusinessListReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{1}
}

func (x *BusinessListReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *BusinessListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BusinessListReq) GetHomestayBusinessId() int64 {
	if x != nil {
		return x.HomestayBusinessId
	}
	return 0
}

type BusinessListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Homestay []*Homestay `protobuf:"bytes,1,rep,name=Homestay,proto3" json:"Homestay,omitempty"`
}

func (x *BusinessListResp) Reset() {
	*x = BusinessListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessListResp) ProtoMessage() {}

func (x *BusinessListResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessListResp.ProtoReflect.Descriptor instead.
func (*BusinessListResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{2}
}

func (x *BusinessListResp) GetHomestay() []*Homestay {
	if x != nil {
		return x.Homestay
	}
	return nil
}

type HomestayListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *HomestayListReq) Reset() {
	*x = HomestayListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayListReq) ProtoMessage() {}

func (x *HomestayListReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayListReq.ProtoReflect.Descriptor instead.
func (*HomestayListReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{3}
}

func (x *HomestayListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *HomestayListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type HomestayListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Homestay []*Homestay `protobuf:"bytes,1,rep,name=Homestay,proto3" json:"Homestay,omitempty"`
}

func (x *HomestayListResp) Reset() {
	*x = HomestayListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayListResp) ProtoMessage() {}

func (x *HomestayListResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayListResp.ProtoReflect.Descriptor instead.
func (*HomestayListResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{4}
}

func (x *HomestayListResp) GetHomestay() []*Homestay {
	if x != nil {
		return x.Homestay
	}
	return nil
}

type GuessListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuessListReq) Reset() {
	*x = GuessListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuessListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuessListReq) ProtoMessage() {}

func (x *GuessListReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuessListReq.ProtoReflect.Descriptor instead.
func (*GuessListReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{5}
}

type GuessListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Homestay []*Homestay `protobuf:"bytes,1,rep,name=Homestay,proto3" json:"Homestay,omitempty"`
}

func (x *GuessListResp) Reset() {
	*x = GuessListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuessListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuessListResp) ProtoMessage() {}

func (x *GuessListResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuessListResp.ProtoReflect.Descriptor instead.
func (*GuessListResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{6}
}

func (x *GuessListResp) GetHomestay() []*Homestay {
	if x != nil {
		return x.Homestay
	}
	return nil
}

type HomestayDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *HomestayDetailReq) Reset() {
	*x = HomestayDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayDetailReq) ProtoMessage() {}

func (x *HomestayDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayDetailReq.ProtoReflect.Descriptor instead.
func (*HomestayDetailReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{7}
}

func (x *HomestayDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HomestayDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Homestay *Homestay `protobuf:"bytes,1,opt,name=Homestay,proto3" json:"Homestay,omitempty"`
}

func (x *HomestayDetailResp) Reset() {
	*x = HomestayDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayDetailResp) ProtoMessage() {}

func (x *HomestayDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayDetailResp.ProtoReflect.Descriptor instead.
func (*HomestayDetailResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{8}
}

func (x *HomestayDetailResp) GetHomestay() *Homestay {
	if x != nil {
		return x.Homestay
	}
	return nil
}

type HomestayBusinessBoss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar   string `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Info     string `protobuf:"bytes,5,opt,name=Info,proto3" json:"Info,omitempty"`
	Rank     int64  `protobuf:"varint,6,opt,name=Rank,proto3" json:"Rank,omitempty"`
}

func (x *HomestayBusinessBoss) Reset() {
	*x = HomestayBusinessBoss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayBusinessBoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayBusinessBoss) ProtoMessage() {}

func (x *HomestayBusinessBoss) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayBusinessBoss.ProtoReflect.Descriptor instead.
func (*HomestayBusinessBoss) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{9}
}

func (x *HomestayBusinessBoss) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomestayBusinessBoss) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HomestayBusinessBoss) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *HomestayBusinessBoss) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *HomestayBusinessBoss) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *HomestayBusinessBoss) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type HomestayBusiness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title     string  `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Info      string  `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	Tags      string  `protobuf:"bytes,4,opt,name=Tags,proto3" json:"Tags,omitempty"`
	Cover     string  `protobuf:"bytes,5,opt,name=Cover,proto3" json:"Cover,omitempty"`
	Star      float32 `protobuf:"fixed32,6,opt,name=Star,proto3" json:"Star,omitempty"`
	IsFav     int64   `protobuf:"varint,7,opt,name=IsFav,proto3" json:"IsFav,omitempty"`
	HeaderImg string  `protobuf:"bytes,8,opt,name=HeaderImg,proto3" json:"HeaderImg,omitempty"`
}

func (x *HomestayBusiness) Reset() {
	*x = HomestayBusiness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayBusiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayBusiness) ProtoMessage() {}

func (x *HomestayBusiness) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayBusiness.ProtoReflect.Descriptor instead.
func (*HomestayBusiness) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{10}
}

func (x *HomestayBusiness) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomestayBusiness) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HomestayBusiness) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *HomestayBusiness) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *HomestayBusiness) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *HomestayBusiness) GetStar() float32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *HomestayBusiness) GetIsFav() int64 {
	if x != nil {
		return x.IsFav
	}
	return 0
}

func (x *HomestayBusiness) GetHeaderImg() string {
	if x != nil {
		return x.HeaderImg
	}
	return ""
}

type GoodBossReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GoodBossReq) Reset() {
	*x = GoodBossReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodBossReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodBossReq) ProtoMessage() {}

func (x *GoodBossReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodBossReq.ProtoReflect.Descriptor instead.
func (*GoodBossReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{11}
}

type GoodBossResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomestayBusinessBoss []*HomestayBusinessBoss `protobuf:"bytes,1,rep,name=HomestayBusinessBoss,proto3" json:"HomestayBusinessBoss,omitempty"`
}

func (x *GoodBossResp) Reset() {
	*x = GoodBossResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodBossResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodBossResp) ProtoMessage() {}

func (x *GoodBossResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodBossResp.ProtoReflect.Descriptor instead.
func (*GoodBossResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{12}
}

func (x *GoodBossResp) GetHomestayBusinessBoss() []*HomestayBusinessBoss {
	if x != nil {
		return x.HomestayBusinessBoss
	}
	return nil
}

type HomestayBusinessListInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomestayBusiness *HomestayBusiness `protobuf:"bytes,1,opt,name=HomestayBusiness,proto3" json:"HomestayBusiness,omitempty"`
	SellMonth        int64             `protobuf:"varint,2,opt,name=SellMonth,proto3" json:"SellMonth,omitempty"`
	PersonConsume    int64             `protobuf:"varint,3,opt,name=PersonConsume,proto3" json:"PersonConsume,omitempty"`
}

func (x *HomestayBusinessListInfo) Reset() {
	*x = HomestayBusinessListInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayBusinessListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayBusinessListInfo) ProtoMessage() {}

func (x *HomestayBusinessListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayBusinessListInfo.ProtoReflect.Descriptor instead.
func (*HomestayBusinessListInfo) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{13}
}

func (x *HomestayBusinessListInfo) GetHomestayBusiness() *HomestayBusiness {
	if x != nil {
		return x.HomestayBusiness
	}
	return nil
}

func (x *HomestayBusinessListInfo) GetSellMonth() int64 {
	if x != nil {
		return x.SellMonth
	}
	return 0
}

func (x *HomestayBusinessListInfo) GetPersonConsume() int64 {
	if x != nil {
		return x.PersonConsume
	}
	return 0
}

type HomestayBussinessListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId   int64 `protobuf:"varint,1,opt,name=LastId,proto3" json:"LastId,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *HomestayBussinessListReq) Reset() {
	*x = HomestayBussinessListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayBussinessListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayBussinessListReq) ProtoMessage() {}

func (x *HomestayBussinessListReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayBussinessListReq.ProtoReflect.Descriptor instead.
func (*HomestayBussinessListReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{14}
}

func (x *HomestayBussinessListReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *HomestayBussinessListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type HomestayBussinessListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info []*HomestayBusinessListInfo `protobuf:"bytes,1,rep,name=Info,proto3" json:"Info,omitempty"`
}

func (x *HomestayBussinessListResp) Reset() {
	*x = HomestayBussinessListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayBussinessListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayBussinessListResp) ProtoMessage() {}

func (x *HomestayBussinessListResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayBussinessListResp.ProtoReflect.Descriptor instead.
func (*HomestayBussinessListResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{15}
}

func (x *HomestayBussinessListResp) GetInfo() []*HomestayBusinessListInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type HomestayBussinessDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *HomestayBussinessDetailReq) Reset() {
	*x = HomestayBussinessDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayBussinessDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayBussinessDetailReq) ProtoMessage() {}

func (x *HomestayBussinessDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayBussinessDetailReq.ProtoReflect.Descriptor instead.
func (*HomestayBussinessDetailReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{16}
}

func (x *HomestayBussinessDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HomestayBussinessDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boss []*HomestayBusinessBoss `protobuf:"bytes,1,rep,name=Boss,proto3" json:"Boss,omitempty"`
}

func (x *HomestayBussinessDetailResp) Reset() {
	*x = HomestayBussinessDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayBussinessDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayBussinessDetailResp) ProtoMessage() {}

func (x *HomestayBussinessDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayBussinessDetailResp.ProtoReflect.Descriptor instead.
func (*HomestayBussinessDetailResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{17}
}

func (x *HomestayBussinessDetailResp) GetBoss() []*HomestayBusinessBoss {
	if x != nil {
		return x.Boss
	}
	return nil
}

type HomestayComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	HomestayId int64   `protobuf:"varint,2,opt,name=HomestayId,proto3" json:"HomestayId,omitempty"`
	Content    string  `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Star       float32 `protobuf:"fixed32,4,opt,name=Star,proto3" json:"Star,omitempty"`
	UserId     int64   `protobuf:"varint,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Nickname   string  `protobuf:"bytes,6,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar     string  `protobuf:"bytes,7,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (x *HomestayComment) Reset() {
	*x = HomestayComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomestayComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayComment) ProtoMessage() {}

func (x *HomestayComment) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayComment.ProtoReflect.Descriptor instead.
func (*HomestayComment) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{18}
}

func (x *HomestayComment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomestayComment) GetHomestayId() int64 {
	if x != nil {
		return x.HomestayId
	}
	return 0
}

func (x *HomestayComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HomestayComment) GetStar() float32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *HomestayComment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HomestayComment) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *HomestayComment) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CommentListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId   int64 `protobuf:"varint,1,opt,name=LastId,proto3" json:"LastId,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *CommentListReq) Reset() {
	*x = CommentListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListReq) ProtoMessage() {}

func (x *CommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListReq.ProtoReflect.Descriptor instead.
func (*CommentListReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{19}
}

func (x *CommentListReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *CommentListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CommentListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomestayComment []*HomestayComment `protobuf:"bytes,1,rep,name=HomestayComment,proto3" json:"HomestayComment,omitempty"`
}

func (x *CommentListResp) Reset() {
	*x = CommentListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_travel_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListResp) ProtoMessage() {}

func (x *CommentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListResp.ProtoReflect.Descriptor instead.
func (*CommentListResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{20}
}

func (x *CommentListResp) GetHomestayComment() []*HomestayComment {
	if x != nil {
		return x.HomestayComment
	}
	return nil
}

var File_travel_proto protoreflect.FileDescriptor

var file_travel_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0xa6, 0x03, 0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x2e, 0x0a, 0x12, 0x48,
	0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x49,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x52, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x52, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x6f, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x6f, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x6f, 0x6f, 0x64, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x46, 0x6f, 0x6f, 0x64, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x48, 0x6f, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x02, 0x52, 0x13, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x48, 0x6f,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x75, 0x0a, 0x0f, 0x42,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x4c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x22, 0x3c, 0x0a, 0x10, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x52, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79,
	0x22, 0x41, 0x0a, 0x0f, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x3c, 0x0a, 0x10, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x52, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x22, 0x39, 0x0a, 0x0d, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x79, 0x52, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x22, 0x23, 0x0a, 0x11,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x64, 0x22, 0x3e, 0x0a, 0x12, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x52, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x79, 0x22, 0x9a, 0x01, 0x0a, 0x14, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61,
	0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x22, 0xbe,
	0x01, 0x0a, 0x10, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x49,
	0x73, 0x46, 0x61, 0x76, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x49, 0x73, 0x46, 0x61,
	0x76, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x67, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x67, 0x22,
	0x0d, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x22, 0x5c,
	0x0a, 0x0c, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4c,
	0x0a, 0x14, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x42, 0x6f, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x14, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79,
	0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x73, 0x73, 0x22, 0xa0, 0x01, 0x0a,
	0x18, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x40, 0x0a, 0x10, 0x48, 0x6f, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x10, 0x48, 0x6f, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x53,
	0x65, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x53, 0x65, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x22,
	0x4e, 0x0a, 0x18, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x4c,
	0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4c, 0x61, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x4d, 0x0a, 0x19, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x04,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2c,
	0x0a, 0x1a, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x1b,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x04, 0x42,
	0x6f, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42,
	0x6f, 0x73, 0x73, 0x52, 0x04, 0x42, 0x6f, 0x73, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x0f, 0x48, 0x6f,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x53, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x44, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x61, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4c, 0x61, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x50, 0x0a,
	0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x3d, 0x0a, 0x0f, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0f,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x32,
	0xf7, 0x03, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x39, 0x0a, 0x0c, 0x68, 0x6f,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2f, 0x0a, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x68, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x73, 0x73, 0x12, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x54, 0x0a, 0x15, 0x68, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x17, 0x68, 0x6f, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x79, 0x42, 0x75, 0x73, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x36, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_travel_proto_rawDescOnce sync.Once
	file_travel_proto_rawDescData = file_travel_proto_rawDesc
)

func file_travel_proto_rawDescGZIP() []byte {
	file_travel_proto_rawDescOnce.Do(func() {
		file_travel_proto_rawDescData = protoimpl.X.CompressGZIP(file_travel_proto_rawDescData)
	})
	return file_travel_proto_rawDescData
}

var file_travel_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_travel_proto_goTypes = []interface{}{
	(*Homestay)(nil),                    // 0: pb.Homestay
	(*BusinessListReq)(nil),             // 1: pb.BusinessListReq
	(*BusinessListResp)(nil),            // 2: pb.BusinessListResp
	(*HomestayListReq)(nil),             // 3: pb.HomestayListReq
	(*HomestayListResp)(nil),            // 4: pb.HomestayListResp
	(*GuessListReq)(nil),                // 5: pb.GuessListReq
	(*GuessListResp)(nil),               // 6: pb.GuessListResp
	(*HomestayDetailReq)(nil),           // 7: pb.HomestayDetailReq
	(*HomestayDetailResp)(nil),          // 8: pb.HomestayDetailResp
	(*HomestayBusinessBoss)(nil),        // 9: pb.HomestayBusinessBoss
	(*HomestayBusiness)(nil),            // 10: pb.HomestayBusiness
	(*GoodBossReq)(nil),                 // 11: pb.GoodBossReq
	(*GoodBossResp)(nil),                // 12: pb.GoodBossResp
	(*HomestayBusinessListInfo)(nil),    // 13: pb.HomestayBusinessListInfo
	(*HomestayBussinessListReq)(nil),    // 14: pb.HomestayBussinessListReq
	(*HomestayBussinessListResp)(nil),   // 15: pb.HomestayBussinessListResp
	(*HomestayBussinessDetailReq)(nil),  // 16: pb.HomestayBussinessDetailReq
	(*HomestayBussinessDetailResp)(nil), // 17: pb.HomestayBussinessDetailResp
	(*HomestayComment)(nil),             // 18: pb.HomestayComment
	(*CommentListReq)(nil),              // 19: pb.CommentListReq
	(*CommentListResp)(nil),             // 20: pb.CommentListResp
}
var file_travel_proto_depIdxs = []int32{
	0,  // 0: pb.BusinessListResp.Homestay:type_name -> pb.Homestay
	0,  // 1: pb.HomestayListResp.Homestay:type_name -> pb.Homestay
	0,  // 2: pb.GuessListResp.Homestay:type_name -> pb.Homestay
	0,  // 3: pb.HomestayDetailResp.Homestay:type_name -> pb.Homestay
	9,  // 4: pb.GoodBossResp.HomestayBusinessBoss:type_name -> pb.HomestayBusinessBoss
	10, // 5: pb.HomestayBusinessListInfo.HomestayBusiness:type_name -> pb.HomestayBusiness
	13, // 6: pb.HomestayBussinessListResp.Info:type_name -> pb.HomestayBusinessListInfo
	9,  // 7: pb.HomestayBussinessDetailResp.Boss:type_name -> pb.HomestayBusinessBoss
	18, // 8: pb.CommentListResp.HomestayComment:type_name -> pb.HomestayComment
	3,  // 9: pb.travel.homestayList:input_type -> pb.HomestayListReq
	1,  // 10: pb.travel.businessList:input_type -> pb.BusinessListReq
	5,  // 11: pb.travel.guessList:input_type -> pb.GuessListReq
	7,  // 12: pb.travel.homestayDetail:input_type -> pb.HomestayDetailReq
	11, // 13: pb.travel.goodBoss:input_type -> pb.GoodBossReq
	14, // 14: pb.travel.homestayBussinessList:input_type -> pb.HomestayBussinessListReq
	7,  // 15: pb.travel.homestayBussinessDetail:input_type -> pb.HomestayDetailReq
	19, // 16: pb.travel.commentList:input_type -> pb.CommentListReq
	4,  // 17: pb.travel.homestayList:output_type -> pb.HomestayListResp
	2,  // 18: pb.travel.businessList:output_type -> pb.BusinessListResp
	12, // 19: pb.travel.guessList:output_type -> pb.GoodBossResp
	8,  // 20: pb.travel.homestayDetail:output_type -> pb.HomestayDetailResp
	12, // 21: pb.travel.goodBoss:output_type -> pb.GoodBossResp
	15, // 22: pb.travel.homestayBussinessList:output_type -> pb.HomestayBussinessListResp
	8,  // 23: pb.travel.homestayBussinessDetail:output_type -> pb.HomestayDetailResp
	20, // 24: pb.travel.commentList:output_type -> pb.CommentListResp
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_travel_proto_init() }
func file_travel_proto_init() {
	if File_travel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_travel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Homestay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuessListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuessListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayBusinessBoss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayBusiness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodBossReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodBossResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayBusinessListInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayBussinessListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayBussinessListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayBussinessDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayBussinessDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomestayComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_travel_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_travel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_travel_proto_goTypes,
		DependencyIndexes: file_travel_proto_depIdxs,
		MessageInfos:      file_travel_proto_msgTypes,
	}.Build()
	File_travel_proto = out.File
	file_travel_proto_rawDesc = nil
	file_travel_proto_goTypes = nil
	file_travel_proto_depIdxs = nil
}
